# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0002_auto_20171023_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayingroup',
            options={'verbose_name': 'День навчання в класі', 'verbose_name_plural': 'Дні навчання в класах'},
        ),
        migrations.AlterModelOptions(
            name='lessoninday',
            options={'verbose_name': 'Номер урока в деякому класі', 'verbose_name_plural': 'Номери уроків в деяких класах'},
        ),
    ]
