# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0004_auto_20171023_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'Навчальний день', 'verbose_name_plural': '1) Навчальні дні'},
        ),
        migrations.AlterModelOptions(
            name='dayingroup',
            options={'verbose_name': 'День навчання в класі', 'verbose_name_plural': '4) Додати день навчання в певний клас'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Клас', 'verbose_name_plural': '1) Класи'},
        ),
        migrations.AlterModelOptions(
            name='lessoninday',
            options={'verbose_name': 'Номер урока в навчальний день в деякому класі', 'verbose_name_plural': '3) Додати урок в навчальний день для певного класу'},
        ),
        migrations.AlterModelOptions(
            name='lessonname',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': '1) Предмети'},
        ),
        migrations.AlterModelOptions(
            name='lessonnumber',
            options={'verbose_name': 'Номер урока в деякому класі', 'verbose_name_plural': '2) Створити урок для класу'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Номер Кабінета', 'verbose_name_plural': '1) Номери Кабінетів'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Вчитель', 'verbose_name_plural': '1) Вчителі'},
        ),
    ]
