# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0007_auto_20171024_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonname',
            name='lesson_name',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
    ]
