# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0008_auto_20171024_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=''),
        ),
    ]
