# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0010_auto_20171027_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableingroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='timetableingroup',
            name='timetable',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Клас', 'verbose_name_plural': 'Створити розклад уроків для класу'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Розклад уроків', 'verbose_name_plural': 'Розклад уроків'},
        ),
        migrations.AlterField(
            model_name='lessonname',
            name='lesson_name',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
        migrations.DeleteModel(
            name='TimetableInGroup',
        ),
    ]
