# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0011_auto_20171027_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('group_name',), 'verbose_name': 'Клас', 'verbose_name_plural': 'Створити розклад уроків для класу'},
        ),
        migrations.AlterModelOptions(
            name='lessonname',
            options={'ordering': ['lesson_name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.AlterModelOptions(
            name='lessonnumber',
            options={'ordering': ('lesson_number',), 'verbose_name': 'Номер уроку', 'verbose_name_plural': 'Номери уроків'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('room_number',), 'verbose_name': 'Номер Кабінета', 'verbose_name_plural': 'Номери Кабінетів'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('teacher_name',), 'verbose_name': 'Вчитель', 'verbose_name_plural': 'Вчителі'},
        ),
        migrations.AlterField(
            model_name='lessonname',
            name='lesson_name',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
