# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0012_auto_20171027_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonname',
            name='lesson_name',
            field=models.CharField(blank=True, default=None, max_length=124, null=True),
        ),
    ]
