# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-28 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0013_auto_20171027_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonname',
            options={'ordering': ('lesson_name',), 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
    ]
